apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-role
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources:
      - eventlisteners
      - triggers
      - triggerbindings
      - triggertemplates
      - clustertriggerbindings
      - clusterinterceptors
      - interceptors
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
